version: 0.2

run-as: Linux-user-name

phases:
  install:
    run-as: Linux-user-name
    runtime-versions:
      nodejs:10
  build:
    commands:
      - echo nothing to do yet

artifacts:
  files:
    - images/*
    - styles/main.class
    - favicon.icon
    - index.html
