version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - images/*
    - styles/main.class
    - favicon.icon
    - index.html
